### ISSUE TITLE
404 errors when requesting lookup.services.cwrc.ca/dbpedia

### ISSUE THREAD

**Issue by Alexandre42** [cwrc/dbpedia-entity-lookup#13]
It looks like this URL is returning a 404 error when requested.
https://github.com/cwrc/dbpedia-entity-lookup/blob/45014a1a5467bfad3be83705d3887cd2c40b1e22/src/index.js#L39

Is there any way to make these calls to work again ? Thanks in advance for your answer.

**Comment by lucaju** [comment]
Thank you @Alexandre42 . The error has been corrected.
