### ISSUE TITLE
not able to resolve the promise which is returned.

### ISSUE THREAD

**Issue by ballu2814** [cwrc/dbpedia-entity-lookup#5]
var result=dbpediaLookup.findPerson({ entity:"Salman khan"});
  result.then(function(value) {
  console.log(value);
 });

This is not working.

**Comment by jchartrand** [comment]
Thank you for submitting this issue.  Please provide more information:

The specific error including stack trace if available.

The environment in which you are running this:  node.js? a browser?

More context, including the rest of your code, your package.json, whether you are you using webpack, browserify, etc.

You must, for example, have imported the npm package into your own code somehow, for example, using the ‘require’ described in the README:

const dbpediaLookup = require('dbpedia-entity-lookup’);

and then have bundled, using browserify (http://browserify.org) or web pack (https://webpack.js.org), and finally included into a html page.  As suggested in the README, this package is meant to be used with:

https://github.com/cwrc/CWRC-PublicEntityDialogs

where you can find more information about usage.

**Comment by ilovan** [comment]
No further feedback received
